# Generated by Django 4.2.13 on 2024-07-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailavleTime',
            new_name='AvailableTime',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='availavle_time',
            new_name='available_time',
        ),
    ]
